姓名: 构建安装包
在……之上:
推:
路径:
      - '*.zip'
workflow_dispatch:
工作:
建立:
连续的：Ubuntu-最新
步骤:
      - uses: 操作/结帐@v4
      - 姓名: 解开拉链
跑: |
unzip-o*.zip
RM*.zip
-uses: 操作/设置-Java@v4
和……一起:
分布: temurin
java版: '21'
      - uses: android-actions/setup-android@v3
      - 姓名: 建立
跑: |
chmod+x gradlew
./gradlew装配释放--无守护程序
      - uses: 操作/上载工件@v4
和……一起:
姓名: CVERoot-释放
路径: app/build/outputs/apk/release/*.apk
